In [3]:
import numpy as np

In [11]:
#n = ([[1,2,3],[1,2,3,4]])
#m = np.array([[1,2,3],[1,2,3,4]])
m= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Tipo de dato: ", m.dtype)
print("forma (shape) del areglo: ", m.shape)
print("tamaño del areglo: ", m.size)
print("Dimension del areglo: ", m.ndim)
print(m)

Tipo de dato:  int32
forma (shape) del areglo:  (3, 3)
tamaño del areglo:  9
Dimension del areglo:  2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
m = np.arange(20)
print(m)
print(m[12:1:-2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 10  8  6  4  2]


### Mascaras
Son caracteristicas (condicionales) que se le dan a nuestras entradas  

In [7]:
a = np.array([1,2,3,4,5,6,7])#array
mascara = [True,True, False,True, False, False, True]
mascara_2 = a > 3
print(a[mascara_2])

[4 5 6 7]


In [8]:
a[a>3] = 0
print(a)

[1 2 3 0 0 0 0]
